spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.229.101:3306/jobs?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource


logging:
  level:
    com:
      sulin:
        jobweb:
          mapper: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.sulin.jobweb.bean